version: '3'

services:
  users_db:
    image: postgres
    container_name: users_db
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  users_service:
    build: 
      context: ./users_service
    container_name: users
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./users_service:/app
    ports:
      - "8000:8000"
    depends_on:
      - users_db
