version: '3'

services:
  users_db:
    image: postgres
    container_name: users_db
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - microservices_network

  users_service:
    build: 
      context: ./users_service
    container_name: users
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./users_service:/app
    ports:
      - "8000:8000"
    depends_on:
      - users_db
    networks:
      - microservices_network

  auth_service:
    build:
      context: ./auth_service
    container_name: auth
    command: bash -c "python -m flask --app auth run --host=0.0.0.0 -p 8001"
    volumes:
      - ./auth_service:/app
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: postgresql://root:root@users_db/users
      SECRET_KEY: secret_key
    depends_on:
      - users_db
    networks:
      - microservices_network

networks:
  microservices_network:
    driver: bridge
